
[qiime]
path = /export/jippe/jsil/projects/16S/RBRA/

size_subsample = 10000

path_python = /export/jippe/jsil/programs/16S/versions/2.0/
path_qiime = ~/export/jippe/miniconda3/envs/qiime2-2022.11

nodes = 1
ntasks_per_node = 1
cpus_per_task = 16
qiime_version = qiime2-2022.11

forward_barcodes_file = sample-metadata.tsv
forward_barcodes_column = BarcodeSequence

forward_primer = GTGYCAGCMGCCGCGGTAA
#GTGCCAGCMGCCGCGGTAA
reverse_primer = CCGYCAATTYMTTTRAGTTT

trim_forward = 5
trim_reverse = 5
length_forward = 200
length_reverse = 190

min_depth = 100
max_depth = 69967
sampling_depth = 20865

path_classifier = /export/jippe/jsil/db/Qiime2/qiime2-2022.11/Silva/138/
classifier = silva-138-99-nb-classifier.qza

; Primersequences, please don't overwrite this info!!!

; 515F:  GTGYCAGCMGCCGCGGTAA
; 926R:  CCGYCAATTYMTTTRAGTTT

; 338F:  ACTCCTACGGGAGGCAGCAG
; 806R:  GGACTACHVGGGTWTCTAAT

; 341F:  CCTACGGGNGGCWGCAG
; 926R:  CCGYCAATTYMTTTRAGTTT

; Available classifiers, please don't overwrite this info!!!

; NB_classifier_SILVA_138_99_16S_515F-926R_QIIME2-2019.10.qza
; NB_classifier_SILVA_132_99_16S_515F-926R_QIIME2-2019.10.qza
; NB_classifier_SILVA_132_99_16S_338F-806R_QIIME2-2019.10.qza
; NB_classifier_MiDAS_4-8-1_16S_515F926R.qza
; NB_classifier_MiDAS_4-8-1_16S_338F806R.qza

