#inputdir: "/export/jippe/jsil/projects/16S/KJOH/04_04_2023/"
#outputdir: "/export/jippe/jsil/projects/16S/KJOH/04_04_2023/output/"


#inputdir: "/export/projects/16S/Macrogen_bkis_versions/190_190/"
#naming_convention: "macrogen_BKIS_08_10_2025_190_190"
forw: 200
reve: 200
inputdir: "/export/projects/16S/BSPE/BMKGENEXW2026060103_14_07_2026/"
naming_convention: "BMKGENEXW2026060103_14_07_2026_BSPE"

forward: "GTGYCAGCMGCCGCGGTAA"
reverse: "CCGYCAATTYMTTTRAGTTT"

tooldir: "/export/jippe/jsil/programs/"
condaenvs: "/export/databases/Conda/22.11.1/yaml_files/jsil/"
qiime_v2: "qiime2-2022.11.16S.01.yaml"
classifier: "/export/databases/Silva/138.1/Qiime/2022.11/silva-138-99-nb-classifier_515f_926R.qza"
#classifier: "/export/databases/Silva/138.1/Qiime/2022.11/silva-138-99-nb-classifier_full_length.qza"