#inputdir: "/export/jippe/jsil/projects/16S/KJOH/04_04_2023/"
#outputdir: "/export/jippe/jsil/projects/16S/KJOH/04_04_2023/output/"

inputdir: "/export/projects/16S/KJOH/08_05_2024_Q17537_full/"
naming_convention: "KJOH_16S_515F_926R_08052024_Q17537_full_KJOH"

forward: "GTGYCAGCMGCCGCGGTAA"
reverse: "CCGYCAATTYMTTTRAGTTT"

tooldir: "/export/jippe/jsil/programs/"
condaenvs: "/export/jippe/jsil/db/conda/yaml_files/bgeu/"
qiime_v2: "qiime2-2022.11.16S.yaml"
classifier: "/export/jippe/jsil/db/Qiime2/qiime2-2022.11/Silva/138/silva-138-99-nb-classifier.qza"
